DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS availability_slots CASCADE;
DROP TABLE IF EXISTS services CASCADE;
DROP TABLE IF EXISTS providers CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          VARCHAR(255) NOT NULL UNIQUE,
    password_hash  VARCHAR(255) NOT NULL,
    full_name      VARCHAR(255) NOT NULL,
    role           VARCHAR(20)  NOT NULL CHECK (role IN ('CUSTOMER', 'PROVIDER')),
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE providers (
    provider_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(user_id),
    name         VARCHAR(255) NOT NULL,
    type         VARCHAR(20)  NOT NULL CHECK (type IN ('COURT', 'COACH')),
    location     VARCHAR(255)
);
CREATE UNIQUE INDEX providers_one_user ON providers (user_id);

CREATE TABLE services (
    service_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id    BIGINT NOT NULL REFERENCES providers(provider_id),
    name           VARCHAR(255) NOT NULL,
    duration_min   INT NOT NULL CHECK (duration_min > 0),
    max_players    INT NOT NULL DEFAULT 1,
    price          DECIMAL(8,2) NOT NULL DEFAULT 0
);

-- A court/coach cannot be listed twice for the same start time.
CREATE TABLE availability_slots (
    slot_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id  BIGINT NOT NULL REFERENCES providers(provider_id),
    service_id   BIGINT NOT NULL REFERENCES services(service_id),
    start_time   TIMESTAMP NOT NULL,
    end_time     TIMESTAMP NOT NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'BOOKED', 'CANCELLED')),
    CHECK (end_time > start_time),
    UNIQUE (provider_id, start_time)
);

-- Appointment rows preserve cancellation history. active_slot_id mirrors
-- slot_id while the appointment is BOOKED and is NULL once CANCELLED, so the
-- plain UNIQUE key below allows exactly one active booking per slot while still
-- permitting a rebooking after cancellation. UNIQUE treats NULLs as distinct in
-- both PostgreSQL and H2, so this backstop is portable.
CREATE TABLE appointments (
    appointment_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_id         BIGINT NOT NULL REFERENCES availability_slots(slot_id),
    user_id         BIGINT NOT NULL REFERENCES users(user_id),
    status          VARCHAR(20) NOT NULL DEFAULT 'BOOKED' CHECK (status IN ('BOOKED', 'CANCELLED')),
    active_slot_id  BIGINT,
    booked_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT appointments_one_active_booking UNIQUE (active_slot_id),
    CONSTRAINT appointments_active_slot_matches CHECK (
        (status = 'BOOKED' AND active_slot_id = slot_id)
        OR (status = 'CANCELLED' AND active_slot_id IS NULL))
);
